<a href="https://colab.research.google.com/github/Worachet-Ch/data_viz_2022/blob/main/Data_Stucture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Structure (โครงสร้างข้อมูล)
การเก็บข้อมูลหลายๆ ตัวไว้ด้วยกันอย่างเป็นระเบียบ

## `list()`
- เก็บง่ายที่สุด
- เก็บอะไรก็ได้
- ลำดับในการเก็บ มีความสำคัญ

In [ ]:
list_a = [1,2,3,4,5,6] # use a [] , square brackets

In [ ]:
list_a

[1, 2, 3, 4, 5, 6]

In [ ]:
list_b = ['ab',2,3.14, list_a] #วิธีเก็บข้อมูลชนิดนึง

In [ ]:
list_b

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]

### indexing การชี้สมาชิกใน list ด้วยเลขลำดับของ list

In [ ]:
list_a[3]

4

In [ ]:
list_b[3]

[1, 2, 3, 4, 5, 6]

In [ ]:
list_b[3][4]

5

In [ ]:
list_a[6] #มันเกินตัวที่ข้อมูลมี

IndexError: ignored

In [ ]:
list_a[-1] #index -1 คือตัวสุดท้ายของ list

6

In [ ]:
list_a[-4] # index -4 เป็นตัวที่3 

3

### การสร้าง `list()` 


In [ ]:
list_x1 = [] #แบบที่ 1 
list_x2 = list() # แบบที่ 2 


In [ ]:
print(list_x1)
print(list_x2)

[]
[]


### เพิ่มสมาชิกเข้าไปใน list ด้วย `append()`

In [ ]:
list_x1.append(2) #เป็นการเพิ่ม 2 ลงใน list

In [ ]:
list_x1

[2]

In [ ]:
list_x1.append(4) #ยิ่งกดรัน ตัวแปรยิ่งถูกใสเพิ่ม
print(list_x1)

[2, 4, 4, 4]


In [ ]:
list_x1[0]

2

### ลบสมาชิกใน list 

In [ ]:
list_x2.append('ha')

In [ ]:
list_x2

['ha', 'ha']

In [ ]:
list_x1.pop() #ลบสมาชิกตัวหลังสุด

4

In [ ]:
list_x1

[2, 4, 4]

In [ ]:
list_x1.pop()
print(list_x1)

[2, 4]


### `len()` ตรวจสอบจำนวนสมาชิก

In [ ]:
print(list_b)
print(len(list_b))

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]
4


In [ ]:
len(list_a) 

6

### String is a list of characters

In [ ]:
st_stat = 'Department of Statistics, Faculty of Science'

In [ ]:
st_stat[10]

' '

In [ ]:
len(st_stat)

44

### List Slicing:

-  `list[จุด เริ่มต้น (ทืบ) :จุดสุดท้าย (โปร่ง)]`
- `list[จุดเริ่มต้น:จุดสุดท้าย:step]`

In [ ]:
list_a

[1, 2, 3, 4, 5, 6]

In [ ]:
list_a[2]

3

### : colon

In [ ]:
list_a[:4] #เอาตัวก่อนหน้าตำแหน่งที่ 4

[1, 2, 3, 4]

In [ ]:
list_a[-3:] # colon เอาจากตัวสุดท้าย นับถอยหลังไป 3 ตัว

[4, 5, 6]

In [ ]:
list_a[1:4] # เริ่มจากตำแหน่ง 1(แต่ไม่เอา 1 ) ถึง 4

[2, 3, 4]

In [ ]:
list_a[:]

[1, 2, 3, 4, 5, 6]

### step

In [ ]:
list_c = [1,2,3,4,5,6,7,8,9,10,11,12]

In [ ]:
list_c[:10:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
list_c[:10:2] #เอาค่าถึงตำแหน่ง 10 และ ห่างกันตำแหน่งที่ 2

[1, 3, 5, 7, 9]

In [ ]:
list_c[::-1]

[12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

### `range()`

In [ ]:
a= list(range(21))

In [ ]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [ ]:
range(21) #เพิ่มเลขจะได้เลข0-21

range(0, 21)

In [ ]:
list(range(1,21)) #กำหนดตั้งแต่ใส่เลข 1-21

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

### HW2 คำนวณเวลาเป็นวินาทีของเวลาต่อไปนี้โดยใช้คำสั่ง split() ช่วย (print ออกมาให้สวยงาม)
- 12:30:15
- 13:41:07
- 09:11:50
- 21:30:15
- 03:10:15

In [ ]:
# EX 01:02:03

a= (1*60*60) + (2*60)+(3)
print(f'01:02:03 แปลงเป็นวินาทีได้ {a} วินาที')

01:02:03 แปลงเป็นวินาทีได้ 3723 วินาที


In [ ]:
# 1.12:30:15
a_1 = '12:30:15'.split(':') # สร้างตัวแปรที่เก็บข้อมูลที่แยกและใช้คำสั่ง split แยก : ออกมา
ans1 = int(a_1[0])*60*60 + int(a_1[1])*60 + int(a_1[2]) # แปลงข้อมูลให้เป็น int (ไม่งั้นคำนวณไม่ได้) แล้วนำมา + กัน
    # ตัวเลขที่นำมา * ต้องอยู่นอกวงเล็กตัวแปร ไม่งั้นจะเป็นการเอาค่าที่อยู่ในตำแหน่งนั้น * กับว่าจะเอาเพิ่มกี่ตัว
print(f'เวลา 12:30:15 แปลงเป็นวินาทีได้เป็น {ans1} วินาที')

เวลา 12:30:15 แปลงเป็นวินาทีได้เป็น 45015 วินาที


In [ ]:
# 2. 13:41:07
a_1 = '13:41:07'.split(':')  # สร้างตัวแปรที่เก็บข้อมูลที่แยกและใช้คำสั่ง split แยก : ออกมา
ans1 = int(a_1[0])*60*60 + int(a_1[1])*60 + int(a_1[2])   # แปลงข้อมูลให้เป็น int (ไม่งั้นคำนวณไม่ได้) แล้วนำมา + กัน 
 # ตัวเลขที่นำมา * ต้องอยู่นอกวงเล็กตัวแปร ไม่งั้นจะเป็นการเอาค่าที่อยู่ในตำแหน่งนั้น * กับว่าจะเอาเพิ่มกี่ตัว
print(f'เวลา 13:41:07 แปลงเป็นวินาทีได้เป็น {ans1} วินาที')

เวลา 13:41:07 แปลงเป็นวินาทีได้เป็น 49267 วินาที


In [ ]:
# 3. 09:11:50
a_1 = '09:11:50'.split(':') # สร้างตัวแปรที่เก็บข้อมูลที่แยกและใช้คำสั่ง split แยก : ออกมา
ans1 = int(a_1[0])*60*60 + int(a_1[1])*60 + int(a_1[2])  # แปลงข้อมูลให้เป็น int (ไม่งั้นคำนวณไม่ได้) แล้วนำมา + กัน 
 # ตัวเลขที่นำมา * ต้องอยู่นอกวงเล็กตัวแปร ไม่งั้นจะเป็นการเอาค่าที่อยู่ในตำแหน่งนั้น * กับว่าจะเอาเพิ่มกี่ตัว
print(f'เวลา 09:11:50 แปลงเป็นวินาทีได้เป็น {ans1} วินาที')

เวลา 09:11:50 แปลงเป็นวินาทีได้เป็น 33110 วินาที


In [ ]:
# 4. 21:30:15
a_1 = '21:30:15'.split(':') # สร้างตัวแปรที่เก็บข้อมูลที่แยกและใช้คำสั่ง split แยก : ออกมา
ans1 = int(a_1[0])*60*60 + int(a_1[1])*60 + int(a_1[2])  # แปลงข้อมูลให้เป็น int (ไม่งั้นคำนวณไม่ได้) แล้วนำมา + กัน 
 # ตัวเลขที่นำมา * ต้องอยู่นอกวงเล็กตัวแปร ไม่งั้นจะเป็นการเอาค่าที่อยู่ในตำแหน่งนั้น * กับว่าจะเอาเพิ่มกี่ตัว
print(f'เวลา 21:30:15 แปลงเป็นวินาทีได้เป็น {ans1} วินาที')

เวลา 21:30:15 แปลงเป็นวินาทีได้เป็น 77415 วินาที


In [ ]:
# 5. 03:10:15
a_1 = '03:10:15'.split(':') # สร้างตัวแปรที่เก็บข้อมูลที่แยกและใช้คำสั่ง split แยก : ออกมา
ans1 = int(a_1[0])*60*60 + int(a_1[1])*60 + int(a_1[2]) # แปลงข้อมูลให้เป็น int (ไม่งั้นคำนวณไม่ได้) แล้วนำมา + กัน 
 # ตัวเลขที่นำมา * ต้องอยู่นอกวงเล็กตัวแปร ไม่งั้นจะเป็นการเอาค่าที่อยู่ในตำแหน่งนั้น * กับว่าจะเอาเพิ่มกี่ตัว
print(f'เวลา 03:10:15 แปลงเป็นวินาทีได้เป็น {ans1} วินาที')

เวลา 03:10:15 แปลงเป็นวินาทีได้เป็น 11415 วินาที


## Dictionary

- คล้าย list()
- indexเป็นอะไรก็ได้ไม่จำเป็นต้องเป็นตัวเลขลำดับ
- ลำดับไม่มีความสำคัญ

### สร้าง Dictionary

### การชี้ สมาชิกใน Dictionary

In [1]:
dict_a = {1:'Happy','N':'New','2022':'Year'} # {} curly brackets

In [2]:
dict_a[1]

'Happy'

In [4]:
dict_a['N']

'New'

In [5]:
dict_a.keys() #ไว้ดู key ในการใช้เรียก

dict_keys([1, 'N', '2022'])

In [6]:
dict_a.values() #ไว้ดู ค่า

dict_values(['Happy', 'New', 'Year'])

### การเพิ่มสมาชิกลงไปใน Dictionary

In [7]:
dict_a[7] = 3.14 # อันหน้าคือ key อันหลังคือค่า values

In [8]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'New'}

In [9]:
dict_a['N'] = 'fsfsfafsf'

In [10]:
dict_a


{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'fsfsfafsf'}

## Numpy Array


- เก็บได้แต่ตัวเลข
- อ้างอิงโดยใช้ พิกัด (2 มิติ ก็มองเป็น Martix)

### 1D array

In [11]:
import numpy

In [16]:
list_A = [1,2,3,4,5]

In [18]:
arr_a = numpy.array(list_A)

In [19]:
arr_a

array([1, 2, 3, 4, 5])

In [21]:
list_A

[1, 2, 3, 4, 5]

In [20]:
arr_a[0]

1

In [22]:
list_A[0]

1

In [23]:
5 * arr_a # Matri (scalar multiplication)

array([ 5, 10, 15, 20, 25])

In [24]:
5 * list_A

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [26]:
arr_b = numpy.array([10,20,30,40,50])

In [27]:
print(arr_a)

[1 2 3 4 5]


In [28]:
arr_a + arr_b

array([11, 22, 33, 44, 55])

In [37]:
arr_a.shape

(5,)

### 2D array

In [30]:
import numpy as np

In [33]:
arr2_z = np.array([[1,2,3],[4,5,6]])

In [35]:
arr2_z

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr2_z.shape

(2, 3)

### np.zeros()

In [53]:
arr2_3_5_0 = np.zeros((3,5))

In [54]:
arr2_3_5_0 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
arr2_3_5_0[1,2] = 9

In [41]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [52]:
arr2_3_5_0[1,2]

1.0

In [43]:
print(list_A) #เปลี่ยนค่าใน list()
list_A[-1] = 'Christmas'
print(list_A)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 'Christmas']


### np.ones()

In [45]:
arr2_4_5_1 = np.ones((4,5))

In [46]:
arr2_4_5_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
arr2_4_5_200 = 200*np.ones((4,5))

In [48]:
arr2_4_5_200

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

### Matrix operation

การบวก ลบ matrix $M \pm N $ บวกลบตัวที่อยู่ตำแหน่งเดียวกัน

In [55]:
arr2_4_5_200 + arr2_3_5_0 # บวก ลบ matrix shape ต้องเท่ากัน

ValueError: ignored

In [56]:
arr2_4_5_200 + arr2_4_5_1

array([[201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.]])

### การคูณ matrix
- $aM$ scalar คูณ Martrix (คูณกระจายเข้าไปทุกตัวของ Matrix)
- $M\times N$ Martrix คูณ Matrix (แถวคูณหลัก)

$aM$

In [57]:
5 * arr_a # Matri (scalar multiplication)

array([ 5, 10, 15, 20, 25])

$M\times N$ (dot product)
- (m,n) $\times$ (n,o) = (m,o) (Shape)

In [59]:
mat_a = np.array([[2,3,5],[4,6,7]])
mat_b = np.array([[1,3,5],[4,6,-7]])
mat_c = np.array([[2,3],[4,6],[7,9]])

In [60]:
mat_a

array([[2, 3, 5],
       [4, 6, 7]])

In [61]:
mat_b

array([[ 1,  3,  5],
       [ 4,  6, -7]])

In [62]:
mat_c

array([[2, 3],
       [4, 6],
       [7, 9]])

axc, bxc,

In [63]:
np.dot(mat_a,mat_c)

array([[ 51,  69],
       [ 81, 111]])

In [64]:
np.dot(mat_b,mat_c)

array([[ 49,  66],
       [-17, -15]])

cxa,cxb

In [65]:
np.dot(mat_c,mat_a)

array([[16, 24, 31],
       [32, 48, 62],
       [50, 75, 98]])

In [68]:
mat_X = np.dot(mat_c,mat_b)
print(mat_X)

[[ 14  24 -11]
 [ 28  48 -22]
 [ 43  75 -28]]


In [67]:
mat_a * mat_b #คูณตำแหน่งเดียวกัน

array([[  2,   9,  25],
       [ 16,  36, -49]])

### Matrix Slicing

In [69]:
mat_X[:2,:2]

array([[14, 24],
       [28, 48]])

HW 3 
1. สร้าง array ที่เป็นรูป ต้น Christmas
2. slica เลข 1 ออกมาจาก array HW3 ด้วยการ slice แค่ครั้งเดียว

In [71]:
HW3 = np.zeros((10,10))
HW3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [72]:
HW3[:,2] = 1 
HW3[::4,4] = 1
HW3[::4,6] = 1
HW3[::4,8] = 1
HW3

array([[0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]])

## Pandas Dataframe (แยกออกไปเป็น Notebook เฉพาะ)